SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";

ALTER TABLE `dropdowns_masters` ADD `testingcomp_id` INT NULL DEFAULT '0' AFTER `deleted`;
COMMIT;
