SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";

CREATE TABLE IF NOT EXISTS `ticket_reportnumbers` ( `ticket_id` INT NOT NULL , `reportnumber_id` INT NOT NULL ) ENGINE = InnoDB DEFAULT CHARSET=utf8;

COMMIT;
